apiVersion: apps/v1
kind: Deployment
metadata:
  name: biplab-banking
  labels:
    app: biplab-banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: biplab-banking-app
  template:
    metadata:
      labels:
        app: biplab-banking-app
    spec:
      containers:
      - name: biplab-banking-container
        image: biplabstudy/banking-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: biplab-banking-service
  labels:
    app: biplab-banking-app
spec:
  selector:
    app: biplab-banking-app

  type: NodePort
  ports:
  - nodePort: 30100
    port: 80
    targetPort: 8081
